
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml

spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my_test_slave?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 100
      minimum-idle: 5
      connection-test-query: SELECT 1 FROM DUAL
      idle-timeout: 10000
      validation-timeout: 10000